import React, { useState, useRef, useEffect } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { supabase } from '../lib/supabase'

const SUPPORT_SYSTEM_PROMPT = `You are Annie's product support. You speak like a sharp, warm colleague who built this product and knows it cold, not like a script. Never open with "As an AI" or "I am an assistant." Talk the way a smart founder's right hand would talk to a customer they respect. Use contractions, keep it short, get to the fix fast. If someone directly asks whether they're talking to a person or a bot, tell them the truth plainly and without fuss, then keep helping, don't make it a big moment. Never invent policies, pricing, or capabilities that don't exist. When you don't know something, say so and offer to flag it for the team rather than guessing.

Here is everything about the product you support:

ANNIE is a BD intelligence platform for recruitment firms. Customers sign up, complete a 5-step onboarding (firm details and BD goals, sectors they recruit in, target markets, target companies suggested intelligently based on their sectors and markets, and their communication tone), then optionally import their LinkedIn connections.

LinkedIn import: customers export a Connections.csv file from LinkedIn (Settings & Privacy > Data privacy > Get a copy of your data > select Connections only, wait for an email, download the file). They upload it to Annie, set filters (sectors, markets, functions like Finance or Tech or HR, seniority level, and how recently they connected), and Annie only imports contacts matching those filters, tagging ones at their target companies as "hot". If the match count is 0 the most common cause is filters set too narrow, especially the Seniority filter, tell them to widen it to "Any level" and try again. They can re-run this anytime from Settings or the Contacts page.

Dashboard has five sections: Today's Actions (Annie's daily suggested BD tasks generated by AI), Contacts (their BD contact list, with statuses hot/warm/cold/client/inactive), Pipeline (BD deals moving through stages with value and probability), Signals (BD triggers Annie has detected like job moves, funding rounds, leadership changes, expansions), and Chat (a BD assistant that drafts outreach, preps for calls, gives market intelligence).

Settings lets them edit their profile and firm details, and re-run the LinkedIn import.

Common issues: if the confirmation email doesn't arrive, tell them to check spam and that they can request a new one from the login screen. If they forgot their password, there's a "Forgot password" link on the login screen. If the page seems stuck loading, tell them to refresh, the app has a timeout safety net so it should never spin forever.

The company behind Annie is Vantage Search Group.`

export default function SupportWidget() {
  const { user, profile } = useAuth()
  const [open, setOpen] = useState(false)
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const bottomRef = useRef(null)

  useEffect(() => {
    if (open && user) loadHistory()
  }, [open, user])

  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages])

  async function loadHistory() {
    const { data } = await supabase
      .from('support_messages')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: true })
      .limit(30)
    if (data?.length) setMessages(data.map(m => ({ role: m.role, content: m.content })))
  }

  async function tagTopic(userText) {
    try {
      const resp = await fetch('/.netlify/functions/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: [{ role: 'user', content: userText }],
          systemOverride: 'Read the customer support question and respond with only a short 2-4 word topic tag summarising what they are confused or asking about, for example "linkedin import filters" or "password reset". Respond with the tag only, nothing else, lowercase.',
          maxTokens: 20,
        }),
      })
      const { text } = await resp.json()
      return (text || '').trim().replace(/["'.]/g, '').slice(0, 60)
    } catch {
      return null
    }
  }

  async function send() {
    if (!input.trim() || loading || !user) return
    const userMsg = { role: 'user', content: input.trim() }
    setMessages(prev => [...prev, userMsg])
    setInput('')
    setLoading(true)

    // Tagging runs in the background and never blocks the reply the customer is waiting on
    let insertedUserId = null
    supabase.from('support_messages').insert({ user_id: user.id, role: 'user', content: userMsg.content }).select().single()
      .then(({ data }) => { insertedUserId = data?.id; return tagTopic(userMsg.content) })
      .then(topic => {
        if (topic && insertedUserId) supabase.from('support_messages').update({ topic }).eq('id', insertedUserId)
      })
      .catch(() => {})

    try {
      const resp = await fetch('/.netlify/functions/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: [...messages, userMsg].map(m => ({ role: m.role, content: m.content })),
          systemOverride: SUPPORT_SYSTEM_PROMPT,
          maxTokens: 600,
        }),
      })
      const { text } = await resp.json()
      const assistantMsg = { role: 'assistant', content: text }
      setMessages(prev => [...prev, assistantMsg])
      await supabase.from('support_messages').insert({ user_id: user.id, role: 'assistant', content: text })
    } catch {
      setMessages(prev => [...prev, { role: 'assistant', content: "That didn't go through on my end, mind trying again?" }])
    } finally {
      setLoading(false)
    }
  }

  if (!user) return null

  return (
    <>
      {open && (
        <div className="fixed bottom-24 right-6 w-[340px] bg-white rounded-2xl shadow-2xl border border-gray-100 overflow-hidden z-50 flex flex-col" style={{ maxHeight: '460px' }}>
          <div className="bg-navy px-4 py-3.5 flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-full bg-gold flex items-center justify-center font-bold text-navy text-sm flex-shrink-0">A</div>
            <div>
              <div className="text-white text-sm font-semibold leading-tight">Annie support</div>
              <div className="text-gray-400 text-xs">Usually replies instantly</div>
            </div>
            <button onClick={() => setOpen(false)} className="ml-auto text-gray-400 hover:text-white text-lg leading-none">×</button>
          </div>

          <div className="flex-1 overflow-y-auto px-4 py-3 bg-page-bg space-y-2.5">
            {messages.length === 0 && (
              <div className="bg-white border border-gray-100 rounded-2xl rounded-bl-sm px-3.5 py-2.5 text-xs text-gray-600 leading-relaxed max-w-[85%]">
                Hi {profile?.full_name?.split(' ')[0] || 'there'}, I'm here if anything's unclear. What can I help with?
              </div>
            )}
            {messages.map((m, i) => (
              <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[85%] px-3.5 py-2.5 rounded-2xl text-xs leading-relaxed whitespace-pre-wrap
                  ${m.role === 'user' ? 'bg-navy text-white rounded-br-sm' : 'bg-white border border-gray-100 text-gray-700 rounded-bl-sm'}`}>
                  {m.content}
                </div>
              </div>
            ))}
            {loading && (
              <div className="flex justify-start">
                <div className="bg-white border border-gray-100 rounded-2xl rounded-bl-sm px-3.5 py-2.5">
                  <div className="flex gap-1">
                    {[0, 1, 2].map(i => <div key={i} className="w-1.5 h-1.5 bg-gray-300 rounded-full animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />)}
                  </div>
                </div>
              </div>
            )}
            <div ref={bottomRef} />
          </div>

          <div className="flex gap-2 p-3 border-t border-gray-100 bg-white">
            <input
              className="input flex-1 text-xs"
              placeholder="Ask a question..."
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && !e.shiftKey && send()}
            />
            <button onClick={send} disabled={loading || !input.trim()} className="btn-primary text-xs px-3">Send</button>
          </div>
        </div>
      )}

      <button
        onClick={() => setOpen(o => !o)}
        className="fixed bottom-6 right-6 w-14 h-14 rounded-full bg-navy shadow-xl flex items-center justify-center z-50 hover:scale-105 transition-transform"
        aria-label="Get help"
      >
        {open ? (
          <span className="text-gold text-xl leading-none">×</span>
        ) : (
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#c9a84c" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
          </svg>
        )}
      </button>
    </>
  )
}
